

clans = [
    {
        "name": "Wolf Clan",
        "overview": "There is a clear focus on military prowess to the extent that the warriors can provide 🍎 Food, 💰 Kröwns, and 😀 Happiness primarily through constant fighting while sustaining a low food consumption. Conquering new territory is facilitated through various means, ranging from increased ⚔️ attack power while outside of friendly territory to Berserker's dominion ability.",
        "starting_bonuses": "Killing a 🐺 Wolf provides 🍖 15 Meat, Brown 🐻 Brown Bear and 🐻‍❄️ Kaija provides 🍖 120 Meat.\nYour military units consume 30% less 🍎 Food and military unit grant 😀 Happiness (see below).\nWhenever you have no military units, the first unit recruited is free (excluding the Warchief). Following units cost starts at 💰 25 Kröwns",
        "fame_bonuses": "👑 200 Fame : Dominion\n Your 🪓 Berserker can colonize cleared areas for free (every 12 months). \n👑 500 Fame : Assault \nYour 🛡️ military units gain a ⚔️ 15% Attack bonus when fighting outside your territory. Dominion cooldown is reduced by 50%.",
        "lore_tree": "https://imgur.com/dHaAEKQ",
        "relic": "⚱️Horn of Managarm: Summons up to 3 White Wolves under your control for 🍎 50 Food each, with the cost being reduced by half if you build it in a Wolf Den tile. You can summon them every 2 months. 3 is the total maximum number; if you summon 3 wolves and lose 2 of them, next time the Horn of Managarm is off cooldown you will be able to summon only 2 wolves.",
    },
    {
        "name": "Raven Clan",
        "overview": "💰 Kröwns and Harbors play central roles for this clan. Money can be produced excessively, while tasks like colonization and exploration can simply be paid for, giving this clan a big edge by spending a less vital resource. 😀 Happiness will rarely be an issue with Harbors and explored areas providing plenty and a wealthy military becomes nearly unstoppable.",
        "starting_bonuses": "Can colonize with 👑 Kröwns instead of 🍎 Food. You can spend 💰 Kröwns to accelerate the arrival of new villagers to your Town Hall.\nAll 💰 Kröwns incomes are increased by 15%.\nTrade routes with the homeland are available and earn more 💰 Kröwns. Great Trades Routes offer a 10% discount.\nCan build the Harbor (replaces Longship Dock) to explore coastal areas and later send Mercenaries attacks. Upgrading a Harbor grants +20% exploration speed.\nEarn 👑 Fame by scouting Neutral Factions and enemy Town Halls.",
        "fame_bonuses": "👑 200 Fame : Mercenaries from Homeland\nYou can hire 🗡️ Mercenaries from your ⚓ Harbor and send them to raid coastal areas without a 🏘️ Town Hall on it. Upgrades for your raids are available at the ⚒️ Forge. You can assign 3 more 🧔‍♂️ Sailors in your ⚓ Harbor with a 🕯️ Lighthouse.\n👑 500 Fame : Sea Supremacy\nYou can send your 🗡️ Mercenaries to coastal zones with a 🏘️ Town Hall. More upgrades for your raids are available at the ⚒️ Forge. Your raids will use Fire Javelins, damaging buildings upon raiding.",
        "lore_tree": "https://imgur.com/mJIzgeX",
        "relic": "⚱️Naglfar : Allows you to send two Son of Hrymr to raid coastal tiles.\nMercenaries are unaffected by ⚒️ Weaponsmith and ⚔️ Gear Upgrade, but they benefit from  🧣Fur Coats.",
    },
    {
        "name": "Rat Clan",
        "overview": "Their dedication means their workers and fighters are ready to die to ensure the clan's survival.",
        "stating_bonuses": "The clan has more villagers but they arrive wounded. Wounded units do not count for Happiness requirement.\nThe clan doesn't have access to 🏠 Houses, but all non-mystic buildings provide housing. Once max population is reached, extra villagers stack in a Population's reserve.\nThe 🏥 Shaman Camp replaces the Healer's Hut and trains 🧙‍♂️ Shamans able to fight and heal multiple units and allies, even outside your territory.\nWhen the clan units kill foes or die, the corpses are cremated at the 🏥 Shaman Camp, producing ᛟ Lore and attracting new villagers faster.\nOverwork replaces the 🍖 Feast and boosts all productions at the expense of your workers' health.",
        "fame_bonuses": "👑 200 Fame : Shamanic Care\nWhile being healed your units consume 30% less 🍎 Food.\n👑 500 Fame : Proliferation\nPopulation's reserve can hold +4 villagers max. The maximum duration of Purification Pyre is extended to 6 months.",
        "lore_tree": "https://imgur.com/aLArvIw",
        "relic": "⚱️Flame of Muspelheim : You can summon 🐗 Garm's Incarnation at a 🏥 Shaman Camp.",
    },
    {
        "name": "Kraken Clan",
        "overview": "The clan's capacity to thrive is tied to the terrain because of its penalties on non-coastal areas. However, with enough access to shores, kraken benefit from fisheries producing good and stable 🍎 food income, which can easily be sold for 💰 kröwns and ᛟ lore. Its unique resource, ⌛ Wyrd, can be scarce at the beginning but will become more abundant as the settlement extends. With high levels of 😀 Happiness thanks to the 👱🏻‍♀️ Norns and its military Knowledges, the Clan of the Kraken will be able to, in the later stages of the game, summon vast armies that can eventually be reinforced by a 👩🏻‍🦰 Valkyrie and deadly 👻 Spectral Warriors.",
        "starting_bonuses": "Colonization and building costs on non-coastal zone are 50% more expensive.\nAll units' attack power is reduced by :⚔️ -30% on non-coastal zone.\nYou can't build ⚓ Longship Dock. Trade Victory is not available to you.\nThe 🛖🎣 Fisherman's Hut is replaced by the 🎣 Fishery. It can be used to fish in both lakes and sea. Fisherman.png Fishermen produce +20% more Food.png Food.\nThe 🍻Brewery is replaced by the 🙏🏻 Hörgr to assign female villagers into 👱🏻‍♀️ Norns. The 👱🏻‍♀️ Norns produce 😀 Happiness and ⌛ Wyrd.\n⌛ Wyrd may be used to activate special abilities. And to turn a 👱🏻‍♀️ Norn into a 👩🏻‍🦰 Valkyrie.",
        "fame_bonuses": "Fame.png 200 Fame : Future Sight\n You gain ⌛400 Wyrd.\nYou are warned of events long before they happen (~5 months).\nDuring the 🦑 attack of the kraken event, your clan is 🍖 feasting.\n👑500 Fame : Howl from The Sea Master\nMilitary units killed outside your territory have a chance to become 👻Spectral Warriors under your control (max 7).\nSpectral warriors bring 😟 unhappiness to the zone controller.",
        "lore_tree": "https://imgur.com/QOZxYTs",
        "relic": "⚱️Edda of Vör : Allows your Norns to earn 👑 Fame, at a rate of 👑 1.2 Fame per month. Grants ⌛ 1000 Wyrd once built.",
    },
    {
        "name": "Squirrel Clan",
        "overview": "Led by the 'warchef' 👨🏻‍🦰 Andhrimnir, the people of the Squirrel generally want to enjoy good food as well as a playful lifestyle. Some (even their allies) would call them mischievous rather than helpful. In the end, nobody quite knows if they are (vaguely) trustworthy friends or just roguish rabble-rousers. Although all agree they can cook!",
        "starting_bonuses": "The clan hoards greedily in anticipation of winter 2 months before it starts and can count on a 30% increase in production during this period. However, they have a harder time during winter itself as they consume more 🍎 Food and 🌲 Wood.\nThe Squirrel clan gather 🍒 Ingredients in its territory, depending on the zone type.\nThe 🍴 Stove replaces the 🍻 Brewery, where 🍳 Cooks can prepare 🍖 Meals, allowing great bonuses. 👨🏻‍🦰 Andhrimnir is your warchief and can be assigned to it to produce more 🍒 Ingredients.\nThe clan can achieve its specific Ratatoskr Victory.",
        "fame_bonuses": "👑 200 Fame : A Helping Hand\nYou receive 🍒 Ingredients of each type by boat and you increase your ingredient storage by 200. You can make Meals for your allies. You unlock Gift routes at the 💱 Trading Post.\n👑 500 Fame : Plot for the Throne\nYou gain Fame based on your extra population compared to your most populous opponent. Arrival of new villagers increases by 5% every 100 👑 Fame.\n👑 1500 Fame : Most Beautiful Banquet\nUnlocks the specific new recipe Banquet of Valhöll. The clan of the Squirrel win the Game when prepared.",
        "lore_tree": "https://imgur.com/W6trmyj",
        "relic": "⚱️Yggdrasil's root : The zone where Yggdrasil's Root is built becomes 'Eldritch'. Every 4 months, another zone becomes eldritch. Units in Eldritch zones benefit from periodical production bonuses. Enemy units in an eldritch zone have a chance to pick a fight with their own kin for 5s.",
    },
    {
        "name": "Horse Clan",
        "overview": "The clan strength resides in its versatility, with heavy focus on mining and ⚒️ upgrades. 👩🏻 Eitria and 🧔🏻‍♂️ Brok are at the center of the clan mechanics, mainly because they are the only ones able to mine 🪨 and 💎, and Improve ⚒️ Forge Tools and Relics. Through excavation, they achieve fast progression through the ᛟ lore tree which ease their clan's development in the best suited direction. The ability to build a second relic widen those possibilities even more.",
        "starting_bonuses": "Eitria and Brok are the 2 clan Warchiefs, they can be recruited in the Forge, instead of the usual Military Camps, for 150 💰, no 💎 needed\nThe Clan does not have access to Mines, Miners or Smiths\nYour Warchiefs can build, repair, mine and forge 20% faster\nVölund's ⚒️ Völund's Forge replaces the regular Forge\nEitria & Brok can build, repair, mine, and forge 20% faster. Eitra has an additional +30% bonus for builds and repairs. Brok has an additional +30% bonus for forges.",
        "fame_bonuses": "Fame.png 200 Fame : Craftsmen\nWhen in the same zone, warchiefs mine and forge 50% faster\nSelling 🪨 or 💎 gives 20% more 💰, trading partner gets twice the amount of those resources and neutral faction's will accept these resources.\n👑 500 Fame : Legacy of the Earth\nZones with or next to an active relic receive 15% production bonus.\n2 🪨 and 2 💎 deposits spawns randomly in your territory. All deposits accumulate 20 🪨 and 10 💎",
        "lore_tree": "https://imgur.com/3arSkhT",
        "relic": "⚱️Dainsleif & Tyrfing : Gives your warchiefs, Eitria and Brok +20% 🩸, +20% ⚔️, +20% 🛡️, +20% mining and +20% forge speed.",
    },
    {
        "name": "Stag Clan",
        "overview": "This clan can achieve 👑 Fame rather quickly while having access to more resources as a solid foundation to kickstart a settlement.",
        "starting_bonuses": "You Start with +75 🍎 Food, 🌲 Wood, 💰 Kröwns and +40 ᛟ Lore.\n The Hall of Skalds replaces the Brewery and produces additional 👑 Fame.",
        "fame_bonuses": "👑 200 Fame : Supplies Each\n 👑 200 Fame gain +50 🍎 Food, 🌲 Wood and 💰 Kröwns, +25 ᛟ Lore and +5 🪨 Stone.\n 👑 500 Fame : Annexation\n For each 👑 200 Fame, Colonization costs are decreased by 5% and unit production is increased by 3%(25% max)\n 👑 1000 Fame : Valorous Leader\n Your warchief gains the Valorous Leader ability and an increase of 100% to his defense and 60% to his health",
        "lore_tree": "https://imgur.com/pAnDJQ4",
        "relic": "⚱ Hlidskjalf : Gives your Warchief the Annexation ability. Whenever your Warchief decolonizes a zone, you colonize it for free.\n As of the Swords and Solace update, the relic now instead allows you to train Einherjar by assigning them to Hlidskjalf."
    },
    {
        "name": "Goat Clan",
        "overview": "The biggest advantage lies in the unrivaled ability to prosper with only little space available. Enhancing any areas with cheap extra building space and buildings that are able to occupy an extra worker can create by far the strongest economy among all the clans. Further enhanced by the option to trade away excess 🍎 Food for massive 💰 Kröwns income.",
        "starting_bonuses": "Start with 1 🐑 Sheep and can build two Sheepfolds.\n Increases the production bonus of your feasts by 20%.\n All Military ⚔ Military Experience suffer -20% penalty.",
        "fame_bonuses": "👑 200 Fame : Shepherd\n Gives 2 free 🐑 Sheeps. You can have an additional ⛺ Sheepfold and their 🍎 Food production is increased by +10%.\n 👑 500 Fame : Team Work\n You gain 1 free Feast per year.\n Your units regenerate during feasts.",
        "lore_tree": "https://imgur.com/DqMcEHZ",
        "relic": "⚱ Eldhrumnir : +20% 🍖 Feast bonus, -50% 🍖 Feast cost. Your units regenerate health during a 🍖 Feast. You can build an additional Sheepfold.",
    },
    {
        "name": "Bear Clan",
        "overview": "The Clan of the Bear is a balanced and adaptable clan. Late game Shield Bearers from this clan are a force to be reckoned with, especially if fighting during winter.",
        "starting_bonuses": "During winter,🍎 Food and 🌲 Firewood penalties are reduced by 30%.\n Instead of having reduced power, your 🛡 Military units gain 10% resistance bonus during winter.\n You can summon Kaija, the Armored Bear for 💰 40 Kröwns and 🍎 40 Food and a Shield 🪓 Shield Maiden. Kaija, the Armored Bear Regenerates and produces food near fish. Shield maiden has more 🛡 defense than regular 🪓 Warchief and replaces it.",
        "fame_bonuses": "👑 200 Fame : Kindred Spirit\n Having 🐻‍❄️ Kaija or the Shield 🪓 Shield Maiden in an area, increases local production by 15%.\n 👑 500 Fame : The Bear Awakens\n You gain 👑 +3 Fame per enemy unit killed in an area with the Shield 🪓 Shield Maiden. Your 🛡 Military units gain 1% ⚔ power per 👑 100 Fame. Kaija, 'The Armored Bear' can now go in enemy territory.",
        "lore_tree": "https://imgur.com/KdJHs1s",
        "relic": "⚱ Scabbard of Gram : Your Warchief wields the sword Gram. Enemies hit by Gram are frozen, along with the area around them. Gives +10% attack, +10% defense to Shield Maiden.",
    },
    {
        "name": "Lynx Clan",
        "overview": "The Clan adopted the graceful but threatening lynxes Brundr & Kaelinn when they were just cubs, who now serve as the eyes of the clans esteemed leader and a force to be reckoned with on the battlefield.",
        "starting_bonuses": "Earn Hunting 🧣 Hunting Trophies on animal kills.\n You can summon 🐈‍⬛ Brundr and 🐈 Kaelinn to your Training Camp.\n 🪓 Mielikki the Beastmaster is weaker than other warchiefs but does not cost iron.\n The Archery 🏹 Archery Range replaces the Axe Thrower to  Axe Thrower Camp. The 🏹 Trackers they train are ranged units shooting a wide variety of arrows.\n The Paths of the Hunter replaces the Military paths. Spend Hunting 🧣 Hunting Trophies to unlock powerful abilities for 🐈‍⬛ Brundr, 🐈 Kaelinn and the 🏹 Trackers.",
        "fame_bonuses": "👑 200 Fame : Lure\n Unlock Mythical Lure for Mielikki. She can place a lure in a non enemy controlled zone, which will periodically attract Mythical animals. They come in higher numbers as time passes. The next 🍖 Feast's 🍎 Food cost is reduced by 5% (up to 50%) per animal you clan killed.\n 👑 500 Fame : Oskoreia\n Unlock the Oskoreia ability for Mielikki. She can sacrifice herself to recall the last and strongest Mythical animals the clan killed. In their spirit form, they come back for a last rampage on earth.",
        "lore_tree": "https://imgur.com/VQsEgP3",
        "relic": "⚱ Glepnir : Allows you to place a trap in a non-enemy zone. Activate on demand to reveal spikes that damage and slow enemies for as long as they are in the zone. Lasts 30 seconds.",
    },
    {
        "name": "Dragon Clan",
        "overview": "Provided proper population management, the clan possess the capacity to grow very strong as the game goes on while early expansion is also facilitated. The ability to recruit 👹 Dragonkin makes the draconic warband one of the fiercest. To sustain this costly army, 🧔🏿‍♂️ Slaves can either be used as an economic advantage or feed the dragon gauge by sacrificing them. The essence gauge grants constant and increasing bonuses as 👑 fame rises.",
        "starting_bonuses": "Your Civilians can go into neutral territory.\n No 😀 Happiness or production penalty for being wounded.\n You start with a Sacrificial Pyre. You can build a Dragonkin Altar instead of other military camps.\n Start with 2 🧔🏿‍♂️ Thralls and only 3 👱🏻‍♂️ Villagers. You can buy thralls from your Longship Docks.",
        "fame_bonuses": "👑 200 Fame : Reluctant Workforce\n Receive 5 🧔🏿‍♂️ Thralls.\n Your Dragon 🔥 Dragon Essence gauge is extended, and bonuses are increased.\n 👑 500 Fame : Tenacious Grudge\n +10% ⚔ attack power against an opponent for each victory condition in which they are ahead of you (💸 Commercial Influence, ᛟ Lore, and 👑 Fame). Your Dragon 🔥 Dragon Essence gauge is complete, and bonuses are increased.",
        "lore_tree": "https://imgur.com/V7U91eN",
        "relic": "⚱ Skull of Hrungnir : Allows you to summon an Undead Giant.",
    },
    {
        "name": "Boar Clan",
        "overview": "Clan of the Boar excels at gathering lore points and is less dependent on stone. They also receive greater benefit from the Altar of Kings and forest tiles.\n Note: Trade routes are disabled for the Boar clan.",
        "starting_bonuses": "The Mender's Hut replaces the Healer's Hut. 🧤 Menders produce ᛟ 1 Lore while not healing instead of food.\n Can Colonize neutral zones with wildlife for an extra cost. Wolves and Brown Bears in the colonized zones become friendly and won't attack your units.\n Each additional territory gives +2 max population.\n Learning a new Lore ᛟ gives 20 Fame 👑 instead of 15.\n No happiness penalties for non-upgraded houses or Town Hall.\n Can only trade with neutral factions.",
        "fame_bonuses": "👑 200 Fame : Heritage\n You gain one free Knowledge, this does not count toward a Lore Victory or Blessing unlock.\n 👑 500 Fame : Greater Blessings\n All blessings have upgraded effects:\n ᛝ Freya: Winter penalty is massively reduced (70% for 🍎 Food, 50% for 🌲 Wood)\n ᚹ Baldr: +5 😀 Happiness and +2 Lore ᛟ production\n ᚠ Jörd: Your army and Upgraded Towers now get +10% ⚔ Attack Power.",
        "lore_tree": "https://imgur.com/CLS2DiX",
        "relic": "⚱ Mask of Gullinbursti : Produce +6 🍎 Food. You can pay 150 ᛟ Lore to summon one Giant 🐗 Giant Boar. It is controllable as long as it is not in combat.",
    },
    {

        "name": "Snake Clan",
        "overview": "This Clan benefits from harassment tactics and an aggressive hit and run playstyle. Additionally, the Stolen Lore allows adaptability for otherwise adverse situations.",
        "starting_bonuses": "You start with your warchief, the young Signy.\n 💎Iron is not needed to summon Signy. She can be summoned from the Skirmisher Camp.\n The Skirmisher Camp is an exclusive building of the clan, it allows to recruit Skirmishers that can go through neutrals foes without being detected.\n The clan doesn't have access to 👑 Fame. Signy grows up, getting stronger and unlocking new abilities instead.\n You can use Swidden Field on your zones to temporarily increase production at the cost of reduced production afterward.\n You can steal Knowledge from any other clan you have encountered.",
        "fame_bonuses": "The Clan of the Snake does not have access to 👑 Fame nor the Fame Victory. Instead, Signy grows more powerful over time.\n Specific bonuses:\n Age 16 (801) : Raised by Wolves\n Signy gains Cloaked. When units use Cloaked among wild creatures, they increase their aggressivity toward enemy clans and prevent aggression toward your clan. When some of those creatures launch an assault, the zone is revealed.\n Age 17 (802) : Shadow of the Wild\n Signy is 50% stronger. Military units gain Cloaked.\n Age 18 (803) : Tears of the Earth\n Signy can use Scorched Earth to burn any zone over 3 months(6 month cooldown).\n Burned zone: All production in that tile is reduced by 50%. Additionally, Snake's unit's and buildings gain +50% attack power ⚔ while they are in a tile that is affected by Scorched Earth. While Signy is casting Scorched Earth, her defense 🛡 is increased by 100%. When not in allied territory Signy also loots resources.\n More details:\n https://imgur.com/gCdFkhJ",
        "lore_tree": "https://imgur.com/ZBK6fHv",
        "relic": "⚱ Gungnir : All military units get 10% dodge chance. Unlocks the 🥷 Stealth ability for all your military units.",
    },
    {
        "name": "Ox Clan",
        "overview": "Clan of the Ox is a military focused clan that can form one of the most powerful armies in the game. Torfin is extremely powerful but also very expensive compared to other warchiefs, so care must be taken to ensure his survival.",
        "starting_bonuses": "Your Warchief is the powerful 🪓 Torfin. He can find Ancestral 🪖 Ancestral equipment from Ancient battlegrounds and equip them to become even stronger.\n Torfin's Throne produces +2 Lore.png while Torfin is not summoned\n Your units are tougher, larger and eat 10% more than the other clans.\n Your units have a +15% attack power and defence bonus.\n Specialized civilian units have a +40% base production bonus, except loremasters.\n Non-upgraded buildings can hold only one unit, and houses hold fewer people.",
        "fame_bonuses": "👑 200 Fame : Military Pressure\n Every non-villager unit receives a 4% production bonus for each military unit you control.\n 👑 500 Fame : The True Hero\n Unlocks Ram ability for 🪓 Torfin, which can target an enemy building with a powerful charge. It causes Torfin to run towards it and destroy it in one headbutt, causing fear amongst enemy units on the way. A few buildings are immune to this attack : non-clan buildings, carved stone and Townhall.",
        "lore_tree": "https://imgur.com/BcG0ndy",
        "relic": "⚱ Aegir : 🪓 Torfin can use Provocation : All enemy units and towers target 🪓 Torfin during a short period and his defense is increased by 100% for 6 seconds.",
    }
]
